-d D:\Nano4KProjects\nano4k_hyperram\impl\gwsynthesis\nano4k_hyperram.vg
-p GW1NSR-4C-QFN48P-6
-pn GW1NSR-LV4CQN48PC6/I5
-cst D:\Nano4KProjects\nano4k_hyperram\src\nano4k_hyperram.cst
-cfg D:\Nano4KProjects\nano4k_hyperram\impl\pnr\device.cfg
-bit
-tr
-ph
-o
-timing
-cst_error
-rtl_gao
